version: '3.8'

services:
  # 🐘 The Database
  db:
    image: postgres:15
    container_name: social-media-db
    environment:
      # Grabbing from .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ☕ The Spring Boot App
  app:
    build: .
    container_name: social-media-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    restart: on-failure
    environment:
      # Injecting .env variables into the Java container
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    volumes:
      - ./uploads:/app/uploads

  # 🚀 The Cache
  redis:
    image: redis:latest
    container_name: social_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: